management:
  endpoints:
    web:
      exposure:
        include: '*'
  info:
    env:
      enabled: true

info:
  application:
    name: tenpo-api
    description: application for TENPO - Backend Sr Software Engineer
    author: Rodrigo Ripoll
    version: '@project.version@'
spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/tenpo-tracks
    username: tenpo-user
    password: tenpo-password
  sql:
    init:
      mode: always

redisUrlConnection: "redis://localhost:6379"

resilience4j:
  retry:
    instances:
      myRetry:
        max-attempts: 3
        wait-duration: 100ms
        enable-exponential-backoff: true
        exponential-backoff-multiplier: 2
  circuitbreaker:
    instances:
      myCircuitBreaker:
        wait-duration-in-open-state: 1m
        permitted-number-of-calls-in-half-open-state: 5
        sliding-window-type: count-based
        sliding-window-size: 5
        minimum-number-of-calls: 10
        slow-call-duration-threshold: 10s
        slow-call-rate-threshold: 20
        failure-rate-threshold: 20

cache:
  duration: 2h

tax:
  expire: 30m

rate-limit:
  default:
    rpm: 10
  alpha:
    rpm: 1000
  beta:
    rpm: 3000

integrations:
  base-url:
    tax: "http://localhost:8081"

springdoc:
  swagger-ui:
    configUrl: /swagger.yaml
