openapi: 3.0.1

info:
  title: API TENPO
  description: Application for TENPO - Backend Sr Software Engineer
  version: 1.0.0

servers:
  - url: http://localhost:8080

paths:
  /accountant/payments/brief:
    post:
      summary: Obtener el resumen de un pago con impuestos
      requestBody:
        description: Objeto PaymentTransaction para calcular los impuestos y obtener el resumen de pago
        required: true
        content:
          application/json:
            schema:
              $ref: '#/components/schemas/PaymentTransaction'
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                $ref: '#/components/schemas/PaymentBrief'
        '400':
          description: Bad Request
        '500':
          description: Internal Server Error - It could be for different reasons, one of them because there is no data in the tax cache and the corresponding api cannot be consulted.
    servers:
      - url: http://localhost:8080
  /accountant/request_log/history:
    get:
      summary: Obtener historial de logs de solicitudes
      parameters:
        - in: query
          name: page
          schema:
            type: integer
            default: 0
          description: Número de página
        - in: query
          name: size
          schema:
            type: integer
            default: 5
            minimum: 1
            maximum: 20
          description: Tamaño de la página (no puede ser menor a 1 ni mayor a 20)
      responses:
        '200':
          description: OK
          content:
            application/json:
              schema:
                type: object
                properties:
                  content:
                    type: array
                    items:
                      $ref: '#/components/schemas/RequestLog'
                  pageable:
                    $ref: '#/components/schemas/pageable'
                  totalPages:
                    type: integer
                  totalElements:
                    type: integer
                  last:
                    type: boolean
                  size:
                    type: integer
                  number:
                    type: integer
                  sort:
                    $ref: '#/components/schemas/sort'
                  numberOfElements:
                    type: integer
                  first:
                    type: boolean
                  empty:
                    type: boolean
        '400':
          description: Bad Request
    servers:
      - url: http://localhost:8080

components:
  schemas:
    RequestLog:
      type: object
      properties:
        id:
          type: integer
        timestamp:
          type: string
          format: date-time
        method:
          type: string
        uri:
          type: string
        status_code:
          type: integer
        response:
          type: object
          description: depende del endpoint el body
    PaymentTransaction:
      type: object
      properties:
        first_tx_amount:
          type: number
          format: double
          description: Monto de la primera transacción de pago
        second_tx_amount:
          type: number
          format: double
          description: Monto de la segunda transacción de pago
    Payments:
      type: object
      properties:
        first_tx_amount:
          type: number
          format: double
          description: Monto de la primera transacción de pago
        second_tx_amount:
          type: number
          format: double
          description: Monto de la segunda transacción de pago
        total_payments:
          type: number
          format: double
          description: Monto total de los pagos
    PaymentBrief:
      type: object
      properties:
        payments:
          $ref: '#/components/schemas/Payments'
          description: Datos de las trasacciones de los pagos
        taxes:
          type: number
          format: float
          description: Monto de los impuestos
        total_amount:
          type: number
          format: float
          description: Monto total
    pageable:
      type: object
      properties:
        sort:
          type: object
          properties:
            empty:
              type: boolean
            sorted:
              type: boolean
            unsorted:
              type: boolean
        offset:
          type: integer
          format: int64
        page_number:
          type: integer
          format: int32
        page_size:
          type: integer
          format: int32
        paged:
          type: boolean
        unpaged:
          type: boolean
      required:
        - sort
        - offset
        - page_number
        - page_size
        - paged
        - unpaged
    last:
      type: boolean
    total_pages:
      type: integer
      format: int32
    total_elements:
      type: integer
      format: int32
    size:
      type: integer
      format: int32
    number:
      type: integer
      format: int32
    sort:
      type: object
      properties:
        empty:
          type: boolean
        sorted:
          type: boolean
        unsorted:
          type: boolean
      required:
        - empty
        - sorted
        - unsorted
    first:
      type: boolean
    number_of_elements:
      type: integer
      format: int32
    empty:
      type: boolean

